steam/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret'}

  root 'users#index'
  resources :users, except: [:new]
  resources :games
  post '/games/addCategory', to: 'games#addCategory'
  delete 'games/:id/:category_id' => 'games#removeCategory'
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

steam/app/models/game.rb
class Game < ApplicationRecord
    has_many :game_categories
    has_many :my_games
    has_many :archives

    mount_uploader :picture, ImageUploader
end

steam/app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:addCategory]
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  
  # GET /games
  # GET /games.json
  def index
    @games = Game.all.paginate(page: params[:page], per_page: 10)
  end

  # GET /games/1
  # GET /games/1.json
  def show
    # GameMailer.new_game(@game).deliver_now
    
    tmp = GamesCategory.where('game_id = '+params[:id].to_s)
    @gameCategories = []

    tmp.each do |gameCategory|
      category = Category.find_by(id: gameCategory.category_id)
      @gameCategories.append(category)
    end

    @categories = Category.all
    @newGameCategory = GamesCategory.new
  end

  def addCategory
    idGame = params[:newCategory][:game_id]
    idCategory = params[:newCategory][:category_id]

    newCategory = GamesCategory.new(game_id: idGame, category_id: idCategory)

    if !GamesCategory.find_by(category_id: idCategory, game_id: idGame)
      newCategory.save
    else
      flash.notice = 'Essa Categoria já existe!'
    end

    redirect_to '/games/'+idGame.to_s
  end

  def removeCategory
    idGame = params[:id]
    idCategory = params[:category_id]

    category = GamesCategory.find_by(game_id: idGame, category_id: idCategory)
    category.destroy

    flash.notice = "Categoria removida com sucesso!"
    redirect_to '/games/'+params[:id].to_s
  end

  # GET /games/new
  def new
    @game = Game.new
    @game.picture = params[:picture]
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :description, :picture, :price, :publication)
    end
end

steam/app/helpers/games_helper.rb
module GamesHelper
end

steam/app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :publication %>
    <%= form.datetime_select :publication %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

steam/app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

steam/app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th>Price</th>
      <th>Publication</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.description %></td>
        <td><%= game.picture.present? %></td>  <!-- Lembrar de remover o '.present?' -->
        <td><%= game.price %></td>
        <td><%= game.publication %></td>
        <td><%= link_to 'Show', game %></td>
        <%if current_user.admin%>
          <td><%= link_to 'Edit', edit_game_path(game) %></td>
          <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @games %>
<%if current_user.admin%>
  <%= link_to 'New Game', new_game_path %>
<%end%>

steam/app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

steam/app/views/games/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @game.description %>
</p>

<p>
  <strong>Picture:</strong>
  <% if @game.picture.present?%>
    <%= image_tag @game.picture.small.url %>
  <% else %>
    <p>No picture available</p>
  <% end %>
</p>

<p>
  <strong>Price:</strong>
  <%= @game.price %>
</p>

<p>
  <strong>Publication:</strong>
  <%= @game.publication %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

<p>Adicionar Categoria:</p>

  <%= form_for(@newGameCategory, as: :newCategory, url: 'addCategory') do |form| %>
    <%= form.hidden_field :game_id, value: @game.id %>

    <%= form.select :category_id, @categories.collect { |category| [category.name, category.id] } %>

    <%= form.submit "Adicionar Categoria" %>
  <% end %>

<h3>Categorias do Jogo:</h3>
  <% @gameCategories.each do |c| %>
    <p><%= c.name %></p>
    <%= link_to 'Deletar categoria', '/games/'+@game.id.to_s+'/'+c.id.to_s, method: :delete %>
  <% end %>